### PR TITLE
encode: fix ENCODE_BUFFER_TOO_SMALL bug for lowpower mode

### PR DESCRIPTION
**Pull request by YuJiankang**
fix issue 675, please check https://github.com/01org/libyami/issues/675 for detail.
Signed-off-by: jkyu <jiankang.yu@intel.com>

### CODE REVIEW

**Comment by xuguangxin** [comment]
@wang-fei could help to verify this?

**Comment by wang-fei** [comment]
verified. all fail case from this link can pass now.
https://github.com/01org/libyami/issues/675.

**Comment by xuguangxin** [comment]
Hi @wang-fei 
https://github.com/01org/libyami/issues/657 maybe same root cause, could you help to verify it too?
thanks

**Comment by wang-fei** [comment]
@xuguangxin , https://github.com/01org/libyami/issues/657 still exist.

**Comment by xuguangxin** [comment]
merged as f051729d0f457f9227d20afcb3c64c2347cd0408, thanks fei for verification

**Pull request closed without merging**
