### PR TITLE
fix build issues

### PR DESCRIPTION
**Pull request by chivakker**
These patches fixes a unnecessary auto-creation of a folder in the examples subfolder and the proper include for drm.h on xf86drm.h, also fix make distclean error.

### CODE REVIEW

**Comment by xuguangxin** [comment]
+1

**Comment by xuguangxin** [comment]
configure:

git clean -dxf && ./autogen.sh --prefix=$LIBYAMI_PREFIX --enable-avformat --enable-tests --enable-gtest=/home/thomas/projects/yami/googletest-release-1.7.0 --enable-v4l2 --enable-debug --enable-dmabuf&& make -j8
it will report:

/usr/bin/ld: ./egl/gles2_help.o: undefined reference to symbol 'eglInitialize'
//usr/lib/x86_64-linux-gnu/mesa-egl/libEGL.so.1: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
make[2]: *** [v4l2decode] Error 1

**Comment by chivakker** [comment]
@xuguangxin  you need to drop --enable-tests from your autogen.sh command.   Added a patch to check for egl when disable-tests-gles (or not test-gles) parameter is given.

**Comment by xuguangxin** [comment]
Greate! thanks.

**Pull request merged**
