### PR TITLE
yamitranscode: implement I/P/B QP setting on CQP mode

### PR DESCRIPTION
**Pull request by wudping**
add --ipqp and --pbqp,
the difference between I and B is the sum of --ipqp and --pbqp.

Signed-off-by: wudping <dongpingx.wu@intel.com>

### CODE REVIEW

**Comment by seanvk** [comment]
lgtm +1, needs verify

**Comment by lizhong1008** [comment]
Verify -1， if I set qp=26, qpip=-2, the encoded p frame qp is 26, not 24.

**Comment by wudping** [comment]
Hi, LiZhong, Is the slice_qp_data in the slice parameter set to -2 ?

**Comment by lizhong1008** [comment]
@wudping ，no， it is 0.

**Comment by lizhong1008** [comment]
https://github.com/01org/libyami/pull/535 should fix the slice_qp_data with negative value.

**Comment by lizhong1008** [comment]
I'll re-verify it once 01org/libyami#535 is merged.

**Comment by xuguangxin** [comment]
Hi @lizhong1008 
Please help verify and merge related patches.thank

**Comment by lizhong1008** [comment]
verify +1 based on 01org/libyami#535.

**Comment by lizhong1008** [comment]
merged as 27db285d77cbe41989b7bc4a10b9b05f25ce1e1b

**Pull request closed without merging**
