### PR TITLE
encode: enable lowpower mode for yamitranscode

### PR DESCRIPTION
**Pull request by YuJiankang**
add lowpower option to yamitranscode.
Signed-off-by: jkyu <jiankang.yu@intel.com>

### CODE REVIEW

**Comment by lizhong1008** [comment]
+1

**Comment by xuguangxin** [comment]
could you  move the low power option above the vp9 encoder specific options?
currently it looks like this
```
VP9 encoder specific options:
   --refmode <VP9 Reference frames mode (default 0 last(previous), gold/alt (previous key frame) | 1 last (previous) gold (one before last) alt (one before gold)> optional
   --lowpower <Enable AVC low power mode (default 0, Disabled)> optional
```

**Comment by YuJiankang** [comment]
update to put low power option above the vp9 encoder specific options

**Comment by xuguangxin** [comment]
merged as 70461e9a5f2d4385cf24cf0352f2f3f0ed442946

**Pull request closed without merging**
