### PR TITLE
add I010/P010 input support and enable HEVC 10bit encoder 

### PR DESCRIPTION
**Pull request by QuPengfei**

### CODE REVIEW

**Comment by xuguangxin** [comment]
It have many conflicts with https://github.com/01org/libyami-utils/pull/15. I will review this after #15 merged. You can comments on #15 too. To see how to make both pull request easier

**Comment by seanvk** [comment]
This will likely collide with #15   Agree that you should test with #15.  But I expect an update to #15 next week.

**Comment by xuguangxin** [comment]
this and https://github.com/01org/libyami/pull/533 will rebased after hevc 10 bits decoder(https://github.com/01org/libyami/pull/638) merged. since https://github.com/01org/libyami/pull/638 will conflit with https://github.com/01org/libyami/pull/533

**Comment by xuguangxin** [comment]
close this since we have #61

**Pull request closed without merging**
